### ISSUE TITLE
redoc-cli does not generate HTML page from split openapi

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/gh-openapi-docs#3]
- This tool uses `openapi` to build the complete openapi spec => this is working when given as input the root, split spec
- This tool uses `redoc-cli` to build the standalone HTML page => silently fail when given as input the root, split spec

**Comment by tschaffter** [comment]
redoc-cli options:

```
Generating standalone ReDoc HTML:
/mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/docs/index.html

indexPath: /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/docs/index.html
OPENAPI_YAML_PATH: /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/openapi.yaml
redocOpts:
```

redoc-cli is actually given as input the compiled openapi spec. +1

**Comment by tschaffter** [comment]
Running the command manually:

```
$ npx redoc-cli bundle --output /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/docs/index.html /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/openapi.yaml
Error: Error opening file "/mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/tags/openapi_spec.md"
ENOENT: no such file or directory, open '/mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/tags/openapi_spec.md'
    at ReadFileContext.callback (/mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/node_modules/redoc/node_modules/json-schema-ref-parser/lib/resolvers/file.js:51:20)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)

Error: ENOENT: no such file or directory, open '/mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/tags/openapi_spec.md'
```

This error does not happen if the tool specify a combined spec in its configuration file.

**Comment by tschaffter** [comment]
When given a combined spec to redoc-cli:

```
$ npx redoc-cli bundle --output /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/docs/index.html /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/openapi.yaml
Prerendering docs

🎉 bundled successfully in: /mnt/c/Users/thoma/Documents/dev/gh-openapi-docs/preview/develop/docs/index.html (985 KiB) [⏱ 1.081s]
```

**Comment by tschaffter** [comment]
The issue is because the split spec is referencing a source file that is not included with the codebase. The missing file is *test/test-spec/split/tags/openapi_spec.md*. The reason this file is not included is likely due to this faulty *.gitignore* rule:

```
$ git check-ignore -v test/test-spec/split/tags/openapi_spec.md
.gitignore:114:openapi* test/test-spec/split/tags/openapi_spec.md
```

Solved by force-adding the file:

```
git add -f test/test-spec/split/tags/openapi_spec.md
```
