### ISSUE TITLE
Fix new issue that appears when running in GH workflow

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/gh-openapi-docs#6]
After updating the dependencies of this project and releasing version 0.3.5, the project `nlpsandbox-schemas` and `rocc-schemas` would if they were to using the new version of this tool.

For example:
https://github.com/Sage-Bionetworks/rocc-schemas/pull/75/checks?check_run_id=2034073824

```
Run npx gh-openapi-docs-ts
Preparing docs for API spec at 'openapi/data-node/openapi.yaml' (undefined)

Cloning 'gh-pages' branch into '/home/runner/work/nlpsandbox-schemas/nlpsandbox-schemas/.ghpages-tmp'
ERROR ENOENT: no such file or directory, open '/tmp/shelljs_aeb0ca94d4a963e71662'
Error: Process completed with exit code 1.
```

Based on the message, the issue may have arisen after updating `shelljs` (`^0.7.0` -> `^0.8.4`). See the [commit](https://github.com/tschaffter/gh-openapi-docs/commit/6fdd8cefe7cf71134f0666c7893ced4424cfbcb9#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R36) that updated this this npm package.

The issue can be reproduced locally. The issue does NOT affect the previous version of `gh-openapi-docs` (0.3.4).

```
tschaffter@DESKTOP-H29C5A0:~/dev2/rocc/rocc-schemas$ rm -fr node_modules/
tschaffter@DESKTOP-H29C5A0:~/dev2/rocc/rocc-schemas$ rm -fr package-lock.json
tschaffter@DESKTOP-H29C5A0:~/dev2/rocc/rocc-schemas$ npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

added 806 packages, and audited 807 packages in 13s

36 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
tschaffter@DESKTOP-H29C5A0:~/dev2/rocc/rocc-schemas$ rm -fr preview
tschaffter@DESKTOP-H29C5A0:~/dev2/rocc/rocc-schemas$ npx gh-openapi-docs-ts
Preparing docs for API spec at 'openapi/openapi.yaml' (fix-gh-openapi-docs-ts)

Cloning 'gh-pages' branch into '/home/tschaffter/dev2/rocc/rocc-schemas/.ghpages-tmp'
ERROR ENOENT: no such file or directory, open '/tmp/shelljs_cfee3b899e5e12265337'
```

**Comment by tschaffter** [comment]
This command generate an error (after setting the silent flag to `false`):

```
    shell.exec(
        `git clone --depth=1 --branch=gh-pages ${config.repoOrigin} .`,
        {silent: false}
    );
```

Command: `npm run build && node ./dist/bundle.js`

Log:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/exec-child.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
ERROR ENOENT: no such file or directory, open '/tmp/shelljs_35b3341e1e1684649066'
```

**Comment by tschaffter** [comment]
Downgrading to `shelljs` version `^0.7.0` fixes the error and the above node command works fine. The following file seems missing from the bundle. This file can be found here:

```
$ find node_modules/ -name "exec-child.js"
node_modules/shelljs/src/exec-child.js
```

**Comment by tschaffter** [comment]
Fixed in the above PR.
